---
abstract: 'Get the response from a public path.'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  HTTP::Request::Common: '0'
  Test::Most: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.037, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Plugin-ResponseFrom
requires:
  Catalyst: '5.90060'
  HTTP::Message::PSGI: '0'
  MIME::Base64: '0'
  Moose::Role: '0'
  Scalar::Util: '0'
  URI: '0'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-Plugin-ResponseFrom/issues
  homepage: https://github.com/jjn1056/Catalyst-Plugin-ResponseFrom
  repository: https://github.com/jjn1056/Catalyst-Plugin-ResponseFrom.git
version: '0.003'
